### ISSUE TITLE
Add ability to remove old configurations to not litter hanging symlinks

### ISSUE THREAD

**Issue by C0rn3j** [NVIDIA/nvidia-container-toolkit#1156]
I use Incus to add a GPU to a container, but doing so creates a symlink over time for each driver version on each upgrade.

These broken symlinks make ldconfig spam every single file each time it is ran.

I raised this [with Incus](https://github.com/lxc/incus/issues/2205#issuecomment-2988228655), but Incus claims there is no clean-up mechanism, so I would like for one to be added if possible.

```yaml
(1/1) upgrading ollama-cuda                                                                                                                                               [----------------------------------------------------------------------------------------------------------] 100%
ldconfig: File /usr/lib/libnvidia-ml.so.570.153.02 is empty, not checked.
ldconfig: File /usr/lib/libnvidia-cfg.so.570.153.02 is empty, not checked.
ldconfig: File /usr/lib/libcuda.so.570.153.02 is empty, not checked.
ldconfig: File /usr/lib/libcudadebugger.so.570.153.02 is empty, not checked.
ldconfig: File /usr/lib/libnvidia-opencl.so.570.153.02 is empty, not checked.
ldconfig: File /usr/lib/libnvidia-gpucomp.so.570.153.02 is empty, not checked.
ldconfig: File /usr/lib/libnvidia-ptxjitcompiler.so.570.153.02 is empty, not checked.
ldconfig: File /usr/lib/libnvidia-allocator.so.570.153.02 is empty, not checked.
ldconfig: File /usr/lib/libnvidia-pkcs11.so.570.153.02 is empty, not checked.
ldconfig: File /usr/lib/libnvidia-pkcs11-openssl3.so.570.153.02 is empty, not checked.
ldconfig: File /usr/lib/libnvidia-nvvm.so.570.153.02 is empty, not checked.

[0] # ls -lah /usr/lib/libnvidia-ml.so.* # <ls> aliased to «lsd»
lrwxrwxrwx root   root    25 B  Sun Jun  8 12:53:41 2025  /usr/lib/libnvidia-ml.so.1 ⇒ libnvidia-ml.so.575.57.08
.rwxr-xr-x root   root     0 B  Tue Jun  3 16:01:30 2025  /usr/lib/libnvidia-ml.so.570.153.02
.rwxr-xr-x nobody nobody 2.2 MB Sun Jun  1 15:22:58 2025  /usr/lib/libnvidia-ml.so.575.57.08
```
