### ISSUE TITLE
request: Option for nvidia-ctk cdi generate to also create .so.1 files.

### ISSUE THREAD

**Issue by GinoBadouri** [NVIDIA/nvidia-container-toolkit#128]
Hi there,

I'm running emby media server with podman on Fedora 39.
I'm generating the cdi file with: ```nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml```
Which seems to work just fine.

However the ffmpeg libraries used with emby look for:
- libcuda.so.1
- libnvidia-encode.so.1
- libnvidia-ptxjitcompiler.so.1

Now by default the nvidia.yaml will only have the full library version like:
```
  - containerPath: /lib64/libnvidia-encode.so.535.113.01
    hostPath: /lib64/libnvidia-encode.so.535.113.01
    options:
    - ro
    - nosuid
    - nodev
    - bind
```

The emby container image doesn't have a ldconfig to generate these for me.
So I'm now manually editing the file manually by adding the same block with: containerPath: /lib64/libnvidia-encode.so.1

This is a bit of a hassle, because after each driver update, I'll have to re-run nvidia-ctk cdi generate and then add 3 additional blocks of code so my containers will have libcuda.so.1, libnvidia-encode.so.1 and libnvidia-ptxjitcompiler.so.1.

So an option for nvidia-ctk cdi generate which automatically adds the symlinks for the "so.1" libraries would be a nice one to have :)

**Comment by klueska** [comment]
The `.so.1` symlinks get created by `ldconfig` when it is executed as a hook at runtime.

**Comment by GinoBadouri** [comment]
But that means the container image has to include a copy of glibc's ldconfig right?
Most container images are very minimal and don't have it.

**Comment by elezar** [comment]
In the NVIDIA Container CLI-based implementation, we would run `ldconfig` on the host. In theory this should be happening in this case too, but it could be that we're not resolving things correctly.

Looking at https://github.com/NVIDIA/nvidia-container-toolkit/blob/53b24618a542025b108239fe602e66e912b7d6e2/cmd/nvidia-ctk/hook/update-ldcache/update-ldcache.go#L76-L104, we are execing `/sbin/ldconfig` from the hook -- which since this is a createContainer hook, should resolve on the host.

Note that we do skip the update if `/etc/ld.so.cache` does not exist in the container and maybe this is incorrect for your use case?

**Comment by GinoBadouri** [comment]
I'm running ```emby/embyserver:beta``` from the dockerhub and I can confirm there is no ```/etc/ld.so.cache``` inside the container.
Sure I can give your branch a try, just tell me which one to checkout.

**Comment by GinoBadouri** [comment]
Sorry I'm still a bit new to this.
I currently have nvidia-ctk installed from the repository: ```nvidia-container-toolkit-base-1.14.3-1.x86_64```
The hook inside /etc/cdi/nvidia.yaml looks like this:
```
  hooks:
  - args:
    - nvidia-ctk
    - hook
    - update-ldcache
    - --folder
    - /lib64
    hookName: createContainer
    path: /usr/bin/nvidia-ctk
```
