### ISSUE TITLE
Getting the following error trying to run an Nvidia/Cuda container in Windows 10: Auto-detected mode as 'legacy' nvidia-container-cli: initialization error: WSL environment detected but no adapters were found: unknown

### ISSUE THREAD

**Issue by dograt** [NVIDIA/nvidia-container-toolkit#155]
I can't find info on this error anywhere! I am running Docker Desktop with WSL. My docker compose file looks like this:

```
version: '3'
services:
    app:
      container_name: "sd"
      build: .
      ports:
      - 8080:8080                        # <LOCAL_PORT>:<CONTAINER_PORT>
      command: nvidia-smi
      tty: true # Make windows happy to keep terminal open
      stdin_open: true # Make windows happy to keep terminal open
      deploy:
        resources:
          reservations:
            devices:
            - driver: nvidia
              capabilities:
                - gpu
                - utility # nvidia-smi
                - compute # CUDA. Required to avoid "CUDA version: N/A"
                - video   # NVDEC/NVENC. For instance to use a hardware accelerated ffmpeg. Skip it if you don't need it
```

And my docker file is simply:

```
FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04
```

I don't even know where to start investigating this. Where could things be going wrong? The `nvidia-smi` command works properly on my host machine, just not within the container.
