### ISSUE TITLE
NVidia Runtime Erros in Nextcloud Compose

### ISSUE THREAD

**Issue by DevilsDesigns** [NVIDIA/nvidia-container-toolkit#194]
Im on Windows 11 Pro with WSL2 and Ubuntu VM and WSL obviously. I succesfully can see nvidia-smi and it shows my gpu in there a GTX 1650 Super. 
```
demonwarrior@Movies4You-NAS:~$ nvidia-smi
Fri Dec 15 23:28:27 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.98.01              Driver Version: 536.99       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1650 ...    On  | 00000000:01:00.0  On |                  N/A |
|  0%   48C    P0              23W / 100W |   1584MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A        26      G   /Xwayland                                 N/A      |
|    0   N/A  N/A        32      G   /Xwayland                                 N/A      |
|    0   N/A  N/A        37      G   /Xwayland                                 N/A      |
+---------------------------------------------------------------------------------------+
```

im attempting to run a docker compose for nextcloud and go-vod for nextcloud memories transcoding.

Docker-compose
```
version: '2'

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - C:\Tools\Nextcloud\db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass?
      - MYSQL_PASSWORD=pass?
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  app:
    image: nextcloud:latest
    restart: always
    ports:
      - 8989:80
    links:
      - db
    volumes:
      - J:/Nextcloud:/data
      - J:/Nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=pass?
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
  go-vod:
    image: radialapps/go-vod
    restart: always
    depends_on:
      - app
#    devices:
#      - /dev/dri:/dev/dri # VA-API (omit for NVENC)
    environment:
      - NEXTCLOUD_HOST=https://memories.domain.com
      - NEXTCLOUD_ALLOW_INSECURE=1 # (self-signed certs or no HTTPS)
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia # (NVENC)
```

```
Errors upon running the container
PS C:\tools\nextcloud> docker compose up -d --force-recreate --remove-orphans
[+] Building 0.0s (0/0)                                                                                  docker:default
[+] Running 2/2
 ✔ Container nextcloud-db-1      Recreated                                                                         0.2s
 ✔ Container nextcloud-app-1     Recreated                                                                         0.2s
 - Container nextcloud-go-vod-1  Creating                                                                          0.0s
Error response from daemon: unknown or invalid runtime name: nvidia
```

i was told by support its a nvidia runtime issue and its not seeing it from the container any ideas on how to fix?
