### ISSUE TITLE
Failed to initialize NVML: Insufficient Permissions

### ISSUE THREAD

**Issue by forestofrain** [NVIDIA/nvidia-container-toolkit#210]
* Running podman rootless returns the error `Failed to initialize NVML: Insufficient Permissions`. 
* Running with root works as expected. 

I only had to change one setting in `config.toml` for my system.

```toml
user = "root:video"
```

I compared the relevant files to a fresh Ubuntu 23 install, where rootless worked. The only difference was the permissions on `/dev/nvidia*`. My distro, gentoo, installs a [config](https://github.com/gentoo/gentoo/blob/master/x11-drivers/nvidia-drivers/files/nvidia-545.conf#L31) that changes the defaults for device file parameters. This was introduced with a [commit on 2021-07-21](https://github.com/gentoo/gentoo/commit/701b87679ae89e02d11be22d235081fa55ae58be#diff-4e0a8c08b7ffe1db012efe78cde0532749149066d61541c218ceb2b09c4ca9b5R14). The [NVIDIA driver FAQ](https://us.download.nvidia.com/XFree86/Linux-x86_64/535.154.05/README/faq.html) provides an example in the FAQ:

#### How and when are the NVIDIA device files created?

```
Whether a user-space NVIDIA driver component does so itself, or invokes nvidia-modprobe, it will default to creating the device files with the following attributes:

      UID:  0     - 'root'
      GID:  0     - 'root'
      Mode: 0666  - 'rw-rw-rw-'
```

```
For example, the NVIDIA driver can be instructed to create device files with UID=0 (root), GID=44 (video) and Mode=0660 by passing the following module parameters to the NVIDIA Linux kernel module:

      NVreg_DeviceFileUID=0
      NVreg_DeviceFileGID=44
      NVreg_DeviceFileMode=0660
```

This looks *reasonable* to me. 

Is this a bug with the container toolkit or is it expected? I would assume that with `ModifyDeviceFiles = 1` that I should not have to change my distro config. 

Possible relevant information below.

## Rootless Error

```bash
podman run --rm --device nvidia.com/gpu=all ubuntu nvidia-smi -L
Failed to initialize NVML: Insufficient Permissions
```

```bash
Octal Permissions    Size User Group Date Modified Name
0660  crw-rw----  195,254 root video 21 Jan 13:39  /dev/nvidia-modeset
0666  crw-rw-rw-    509,0 root root  21 Jan 13:39  /dev/nvidia-uvm
0666  crw-rw-rw-    509,1 root root  21 Jan 13:39  /dev/nvidia-uvm-tools
0660  crw-rw----    195,0 root video 21 Jan 13:39  /dev/nvidia0
0660  crw-rw----  195,255 root video 21 Jan 13:39  /dev/nvidiactl
```

```bash
cat /proc/driver/nvidia/params
ModifyDeviceFiles: 1
DeviceFileUID: 0
DeviceFileGID: 27
DeviceFileMode: 432
```

## Rootless Success

After adding a config override with file mode `0666`, podman rootless works as expected.
```
options nvidia NVreg_DeviceFileMode=0666
```

```bash
podman run --rm --device nvidia.com/gpu=all ubuntu nvidia-smi -L                                                                 13:51:17
GPU 0: NVIDIA GeForce RTX 3080 (UUID: GPU-...)
```

```bash
Octal Permissions    Size User Group Date Modified Name
0666  crw-rw-rw-  195,254 root video 20 Jan 16:27  /dev/nvidia-modeset
0666  crw-rw-rw-    509,0 root root  20 Jan 16:27  /dev/nvidia-uvm
0666  crw-rw-rw-    509,1 root root  20 Jan 16:27  /dev/nvidia-uvm-tools
0666  crw-rw-rw-    195,0 root video 20 Jan 16:27  /dev/nvidia0
0666  crw-rw-rw-  195,255 root video 20 Jan 16:27  /dev/nvidiactl
```

```bash
cat /proc/driver/nvidia/params
ModifyDeviceFiles: 1
DeviceFileUID: 0
DeviceFileGID: 27
DeviceFileMode: 438
```

**Comment by elezar** [comment]
@forestofrain this is something that we're aware of, but haven't really found the correct solution for. On most systems it's limited to DRM devices nodes that have `root:video` ownership. As you point out, however, this is dependent on the driver parameters.

One thing we're considering is https://github.com/cncf-tags/container-device-interface/issues/175 where the spec will include the additional GIDs that are required in the container to have access to the device nodes when these are created with `0660` permissions and not `0666`.

In our testing, it was also not quite clear if setting the GID in the CDI specification would have the same effect. 

Would you be able to confirm this on your end. That is to say:

1. Generate a CDI specification using `nvidia-ctk cdi generate`
2. Add the relevant [`gid` field](https://github.com/cncf-tags/container-device-interface/blob/main/specs-go/config.go#L46) to the device nodes that require it (`/dev/nvidia-modeset`, `/dev/nvidia0`, `/dev/nvidiactl`). For example:
```
  deviceNodes:
  - path: /dev/nvidia-modeset
    gid: 27
  - path: /dev/nvidiactl
    gid: 27
```

Then repeat your experiments.

If this works as expected, then the spec extension is not required and we can work on updating our generated spec to include the required GID information.

**Comment by forestofrain** [comment]
Same permission error. Any other information you need?

```bash
podman run --rm --device nvidia.com/gpu=all ubuntu nvidia-smi -L
Failed to initialize NVML: Insufficient Permissions
```

```bash
podman run --rm --group-add=27 --device nvidia.com/gpu=all ubuntu nvidia-smi -L
Failed to initialize NVML: Insufficient Permissions
```

My `/etc/cdi/nvidia.yaml` with your suggested changes. **Note** my 3080 is only for compute and my graphics an Arc 770. 
```yaml
---
cdiVersion: 0.5.0
containerEdits:
  deviceNodes:
  - path: /dev/nvidia-modeset
    gid: 27
  - path: /dev/nvidia-uvm
  - path: /dev/nvidia-uvm-tools
  - path: /dev/nvidiactl
    gid: 27
  hooks:
  - args:
    - nvidia-ctk
    - hook
    - update-ldcache
    - --folder
    - /usr/lib64
    hookName: createContainer
    path: /usr/sbin/nvidia-ctk
  mounts:
  - containerPath: /opt/bin/nvidia-cuda-mps-control
    hostPath: /opt/bin/nvidia-cuda-mps-control
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /opt/bin/nvidia-cuda-mps-server
    hostPath: /opt/bin/nvidia-cuda-mps-server
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /opt/bin/nvidia-debugdump
    hostPath: /opt/bin/nvidia-debugdump
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /run/nvidia-persistenced/socket
    hostPath: /run/nvidia-persistenced/socket
    options:
    - ro
    - nosuid
    - nodev
    - bind
    - noexec
  - containerPath: /usr/lib64/libEGL_nvidia.so.545.29.06
    hostPath: /usr/lib64/libEGL_nvidia.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libGLESv1_CM_nvidia.so.545.29.06
    hostPath: /usr/lib64/libGLESv1_CM_nvidia.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libGLESv2_nvidia.so.545.29.06
    hostPath: /usr/lib64/libGLESv2_nvidia.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libGLX_nvidia.so.545.29.06
    hostPath: /usr/lib64/libGLX_nvidia.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libcuda.so.545.29.06
    hostPath: /usr/lib64/libcuda.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libcudadebugger.so.545.29.06
    hostPath: /usr/lib64/libcudadebugger.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libnvcuvid.so.545.29.06
    hostPath: /usr/lib64/libnvcuvid.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libnvidia-allocator.so.545.29.06
    hostPath: /usr/lib64/libnvidia-allocator.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libnvidia-cfg.so.545.29.06
    hostPath: /usr/lib64/libnvidia-cfg.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libnvidia-egl-gbm.so.1.1.1
    hostPath: /usr/lib64/libnvidia-egl-gbm.so.1.1.1
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libnvidia-eglcore.so.545.29.06
    hostPath: /usr/lib64/libnvidia-eglcore.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libnvidia-encode.so.545.29.06
    hostPath: /usr/lib64/libnvidia-encode.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libnvidia-fbc.so.545.29.06
    hostPath: /usr/lib64/libnvidia-fbc.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libnvidia-glcore.so.545.29.06
    hostPath: /usr/lib64/libnvidia-glcore.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libnvidia-glsi.so.545.29.06
    hostPath: /usr/lib64/libnvidia-glsi.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libnvidia-glvkspirv.so.545.29.06
    hostPath: /usr/lib64/libnvidia-glvkspirv.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libnvidia-gpucomp.so.545.29.06
    hostPath: /usr/lib64/libnvidia-gpucomp.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libnvidia-gtk3.so.545.29.06
    hostPath: /usr/lib64/libnvidia-gtk3.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libnvidia-ml.so.545.29.06
    hostPath: /usr/lib64/libnvidia-ml.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libnvidia-ngx.so.545.29.06
    hostPath: /usr/lib64/libnvidia-ngx.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libnvidia-nvvm.so.545.29.06
    hostPath: /usr/lib64/libnvidia-nvvm.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libnvidia-opencl.so.545.29.06
    hostPath: /usr/lib64/libnvidia-opencl.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libnvidia-opticalflow.so.545.29.06
    hostPath: /usr/lib64/libnvidia-opticalflow.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libnvidia-pkcs11-openssl3.so.545.29.06
    hostPath: /usr/lib64/libnvidia-pkcs11-openssl3.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libnvidia-ptxjitcompiler.so.545.29.06
    hostPath: /usr/lib64/libnvidia-ptxjitcompiler.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libnvidia-rtcore.so.545.29.06
    hostPath: /usr/lib64/libnvidia-rtcore.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libnvidia-tls.so.545.29.06
    hostPath: /usr/lib64/libnvidia-tls.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libnvidia-wayland-client.so.545.29.06
    hostPath: /usr/lib64/libnvidia-wayland-client.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/lib64/libnvoptix.so.545.29.06
    hostPath: /usr/lib64/libnvoptix.so.545.29.06
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/sbin/nvidia-persistenced
    hostPath: /usr/sbin/nvidia-persistenced
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/sbin/nvidia-smi
    hostPath: /usr/sbin/nvidia-smi
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /lib/firmware/nvidia/545.29.06/gsp_ga10x.bin
    hostPath: /lib/firmware/nvidia/545.29.06/gsp_ga10x.bin
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /lib/firmware/nvidia/545.29.06/gsp_tu10x.bin
    hostPath: /lib/firmware/nvidia/545.29.06/gsp_tu10x.bin
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/share/egl/egl_external_platform.d/10_nvidia_wayland.json
    hostPath: /usr/share/egl/egl_external_platform.d/10_nvidia_wayland.json
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/share/egl/egl_external_platform.d/15_nvidia_gbm.json
    hostPath: /usr/share/egl/egl_external_platform.d/15_nvidia_gbm.json
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/share/glvnd/egl_vendor.d/10_nvidia.json
    hostPath: /usr/share/glvnd/egl_vendor.d/10_nvidia.json
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/share/vulkan/icd.d/nvidia_icd.json
    hostPath: /usr/share/vulkan/icd.d/nvidia_icd.json
    options:
    - ro
    - nosuid
    - nodev
    - bind
  - containerPath: /usr/share/vulkan/implicit_layer.d/nvidia_layers.json
    hostPath: /usr/share/vulkan/implicit_layer.d/nvidia_layers.json
    options:
    - ro
    - nosuid
    - nodev
    - bind
devices:
- containerEdits:
    deviceNodes:
    - path: /dev/nvidia0
      gid: 27
    - path: /dev/dri/card1
    - path: /dev/dri/renderD129
    hooks:
    - args:
      - nvidia-ctk
      - hook
      - create-symlinks
      - --link
      - ../card1::/dev/dri/by-path/pci-0000:01:00.0-card
      - --link
      - ../renderD129::/dev/dri/by-path/pci-0000:01:00.0-render
      hookName: createContainer
      path: /usr/sbin/nvidia-ctk
    - args:
      - nvidia-ctk
      - hook
      - chmod
      - --mode
      - "755"
      - --path
      - /dev/dri
      hookName: createContainer
      path: /usr/sbin/nvidia-ctk
  name: "0"
- containerEdits:
    deviceNodes:
    - path: /dev/nvidia0
      gid: 27
    - path: /dev/dri/card1
    - path: /dev/dri/renderD129
    hooks:
    - args:
      - nvidia-ctk
      - hook
      - create-symlinks
      - --link
      - ../card1::/dev/dri/by-path/pci-0000:01:00.0-card
      - --link
      - ../renderD129::/dev/dri/by-path/pci-0000:01:00.0-render
      hookName: createContainer
      path: /usr/sbin/nvidia-ctk
    - args:
      - nvidia-ctk
      - hook
      - chmod
      - --mode
      - "755"
      - --path
      - /dev/dri
      hookName: createContainer
      path: /usr/sbin/nvidia-ctk
  name: all
kind: nvidia.com/gpu
```
