### ISSUE TITLE
Enabling this for compose files

### ISSUE THREAD

**Issue by RiffyDivine** [NVIDIA/nvidia-container-toolkit#422]
Sorry to ask a dumb question but I keep seeing different answers and just wanted a clear one. What do I add into my docker compose files to have them make use of the GPU in the system? I already have the NCT installed fine and the test container from nvidia shows the nvidia-smi so it is working but none of my other containers seem to see it.

One of the major ones I am trying to get working is a dind kasm setup which because it can't seem to get at the gpu the desktops won't work. So I just want to make sure I got the right arguments in my files.

**Comment by trxcllnt** [comment]
I don't know if this is still the way, but this is how I've done it in the past:

```yaml
services:
  gpu-container:
    image: nvidia/cuda:12.3.2-base-ubuntu22.04
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
```
