### ISSUE TITLE
cdi: missing `nvidia-uvm` `deviceNodes`

### ISSUE THREAD

**Issue by Timost** [NVIDIA/nvidia-container-toolkit#50]
Hi,

Thank you for `nvidia-container-toolkit` 🙏

I think the currently generated cdi file is missing `nvidia-uvm` `deviceNodes` for podman.

I'm using `nvidia-container-toolkit` `v1.12.0` with `podman` `4.3.1` on an Ubuntu 22.04 server with a Nvidia Tesla P100 GPU.
I use `pytorch` inside a rootless podman container.

I have installed the nvidia drivers with `ubuntu-drivers autoinstall`.

I have generated the `cdi` configuration file using `nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml`.

The generated file starts with:

```yaml
---
cdiVersion: 0.5.0
containerEdits:
  deviceNodes:
  - path: /dev/nvidiactl
  hooks:
  - args:
    - nvidia-ctk
    - hook
    - update-ldcache
    - --folder
    - /lib/x86_64-linux-gnu
    hookName: createContainer
    path: /usr/bin/nvidia-ctk
...
```

When using this configuration file as-is, `nvidia-smi` works fine but CUDA isn't detected inside the container:
```shell
$ python
>>> import torch
>>> torch.cuda.is_available()
False
```
I have tried with both rootful podman and rootless podman.

After some digging, adding the following `devicesNodes` solves the issue:

```yaml
---
cdiVersion: 0.5.0
containerEdits:
  deviceNodes:
  - path: /dev/nvidiactl
  - path: /dev/nvidia-modeset
  - path: /dev/nvidia-uvm-tools
  - path: /dev/nvidia-uvm
  ...
```
