### ISSUE TITLE
where is the docs of /etc/nvidia-container-runtime/config.toml?

### ISSUE THREAD

**Issue by yxxhero** [NVIDIA/nvidia-container-toolkit#572]
where is the docs of /etc/nvidia-container-runtime/config.toml? 

thanks so much.

**Comment by loveforever330** [comment]
Here I found some documentation that might be useful to you, [click here](https://github.com/NVIDIA/nvidia-container-toolkit/tree/main/cmd/nvidia-container-runtime)

**Comment by yxxhero** [comment]
@loveforever330 thanks so much. but it's not complete.

**Comment by loveforever330** [comment]
@yxxhero I'm so sorry for that .

**Comment by yxxhero** [comment]
@loveforever330 thanks so much again.

**Comment by dinhanhx** [comment]
it would be very helpful, if someone explains to me why do I need to uncomment `no-cgroups = False` like this,
```toml
[nvidia-container-cli]
#debug = "/var/log/nvidia-container-toolkit.log"
environment = []
#ldcache = "/etc/ld.so.cache"
ldconfig = "@/sbin/ldconfig.real"
load-kmods = true
#no-cgroups = false
#path = "/usr/bin/nvidia-container-cli"
#root = "/run/nvidia/driver"
#user = "root:video"
```
By doing this, other users can use docker with nvidia runtime? Why?
