### ISSUE TITLE
k3d Can't Access specific devices Error:  nvidia-container-cli: mount error

### ISSUE THREAD

**Issue by zhuima** [NVIDIA/nvidia-container-toolkit#646]
## os version

`Ubuntu 20.04.6 LTS`

## docker version

```
Client: Docker Engine - Community
 Version:           27.1.1
 API version:       1.46
 Go version:        go1.21.12
 Git commit:        6312585
 Built:             Tue Jul 23 19:56:56 2024
 OS/Arch:           linux/amd64
 Context:           default
```

## docker-compose 

`Docker Compose version v2.29.1`

## nvidia-smi info

`NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4  
`
## compose file

```
services:
  test:
    image: xxx/k3s-agent:v100
    command:
      - agent
      - --server=https://10.1.1.1:6443
      - --disable-apiserver-lb
      - --node-name=worker
      - --with-node-id
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0', '3']
            capabilities: [gpu]
```
## gpu devices

```
0000:1b:00.0
0000:1c:00.0
0000:1f:00.0
0000:23:00.0
0000:35:00.0
0000:36:00.0
0000:39:00.0
0000:3d:00.0
```

## error logs

```
 k3s-agent    | 	rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
k3s-agent    | 	nvidia-container-cli: mount error: stat failed: /proc/driver/nvidia/gpus/0000:1c:00.0: no such file or directory: unknown
```
